/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 robot.gltf --transform 
Files: robot.gltf [12.43MB] > robot-transformed.glb [994.9KB] (92%)
Author: Mora (https://sketchfab.com/MoraAzul)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cute-robot-9c470c850e764357916f34acf2d0a74b
Title: Cute Robot
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/robot-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes._rootJoint} />
      <mesh geometry={nodes.G_Planta_MAT_Planta_0.geometry} material={materials.MAT_Planta} position={[-66.679, 0.077, 42.35]} rotation={[-Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.Object_6.geometry} material={materials.MAT_Robot} skeleton={nodes.Object_6.skeleton} />
      <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.Mat_Transparencia} skeleton={nodes.Object_7.skeleton} />
      <skinnedMesh geometry={nodes.Object_8.geometry} material={materials.MAT_Emisivo} skeleton={nodes.Object_8.skeleton} />
      <skinnedMesh geometry={nodes.Object_9.geometry} material={materials.MAT_Burbujas} skeleton={nodes.Object_9.skeleton} />
      <skinnedMesh geometry={nodes.Object_11.geometry} material={materials.MAT_Robot} skeleton={nodes.Object_11.skeleton} />
      <skinnedMesh geometry={nodes.Object_13.geometry} material={materials.MAT_Robot} skeleton={nodes.Object_13.skeleton} />
      <skinnedMesh geometry={nodes.Object_15.geometry} material={materials.MAT_Robot} skeleton={nodes.Object_15.skeleton} />
      <skinnedMesh geometry={nodes.Object_17.geometry} material={materials.MAT_Robot} skeleton={nodes.Object_17.skeleton} />
      <skinnedMesh geometry={nodes.Object_19.geometry} material={materials.MAT_Robot} skeleton={nodes.Object_19.skeleton} />
      <skinnedMesh geometry={nodes.Object_21.geometry} material={materials.MAT_Robot} skeleton={nodes.Object_21.skeleton} />
      <skinnedMesh geometry={nodes.Object_23.geometry} material={materials.MAT_Robot} skeleton={nodes.Object_23.skeleton} />
    </group>
  )
}

useGLTF.preload('/robot-transformed.glb')
