export { default as Hero } from "./Hero/Hero"
export { default as Who } from "./Who/Who"
export { default as Works } from "./Works/Works"
export { default as Contact } from "./Contact/Contact"
export { default as Navbar } from "./Navbar/Navbar"
